cd ..
python run_fashion_pyramid_occ+attn.py \
 --id=fashion_v7_sc_attn_reg_in_mask_tps_sim \
 --K=3 \
 --gpu=2\
 --phase 'train'\
 --align_corner\
 --batch_size 4 \
 --lr 1e-4 \
 --lr_D 1e-5 \
 --use_adv \
 --use_spectral_D \
 --path_to_dataset '/home/ljw/playground/Global-Flow-Local-Attention/dataset/fashion'\
 --anno_size 256 176 \
 --use_correctness \
 --use_flow_reg\
 --use_pose_decoder \
 --use_bone_RGB \
 --lambda_flow_reg 0.0025\
 --use_attn_reg\
 --lambda_attn_reg 1\
 --use_tps_sim\
 --joints_for_cos_sim 4\
 --model_save_freq 5000 \
 --flow_exp_name 'fashion_pretrain_flow_v0_with_occ_1shot_20201201'\
 --which_flow_epoch 'epoch_35_batch_4000_G'
